
default: &default
  adapter: postgresql
  encoding: unicode
  username: sample_api_app
  pool: 5

development:
  <<: *default
  database: sample_api_app_development
  password: password1

test:
  <<: *default
  database: sample_api_app_test
  password: password1

production:
  <<: *default
  database: sample_api_app_production
  password: <%= ENV['SAMPLE_API_APP_DATABASE_PASSWORD'] %>