
default: &default
  adapter: postgresql
  encoding: unicode
  username: sample_app_for_kian
  pool: 5

development:
  <<: *default
  database: sample_app_for_kian_development
  password: password1

test:
  <<: *default
  database: sample_app_for_kian_test
  password: password1

production:
  <<: *default
  database: sample_app_for_kian_production
  password: <%= ENV['SAMPLE_APP_FOR_KIAN_DATABASE_PASSWORD'] %>